export const MOCK_PAGES = {

  // ── Brand Systems ──────────────────────────────────────────────────────────

  'what-does-a-brand-system-include': {
    heroHeadline: 'What does a brand system actually include?',
    seoTitle: 'What does a brand system actually include? | Super Conscious',
    heroAnswer: 'A brand system is a complete set of decisions about how your company looks, sounds, and presents itself. It covers visual identity, messaging, voice, and the tools your team needs to stay consistent without asking a designer every time.',
    body: [
      { _type: 'headingBlock', heading: 'More than a logo' },
      { _type: 'paragraphBlock', text: 'Most companies think brand is a logo and some colors. A brand system is the logic underneath: why those colors, what they mean, and how they flex across every surface you use.' },
      { _type: 'paragraphBlock', text: 'It includes typography rules, spacing principles, photography direction, and copy guidelines. The kind of decisions that normally live in one designer\'s head, documented so anyone on your team can execute consistently.' },
      { _type: 'headingBlock', heading: 'What it covers' },
      { _type: 'paragraphBlock', text: 'A full brand system from Super Conscious includes logo and mark system, color palette with usage rules, typography stack, verbal identity (voice, tone, messaging framework), social and presentation templates, and a brand guidelines doc your whole team can use.' },
    ],
    processSteps: [
      { label: 'Discovery', description: 'We learn your market, audience, and competitive landscape before we design anything.' },
      { label: 'Strategy', description: 'Positioning, personality, and messaging defined as a brief before we touch visuals.' },
      { label: 'Design', description: 'Visual identity built from the strategy: logo, color, type, and supporting elements.' },
      { label: 'System', description: 'Templates, guidelines, and documentation so your team can use it without us.' },
    ],
    faqs: [
      { question: 'How long does a brand system take?', answer: 'Most brand system engagements run 8–12 weeks depending on scope. Discovery and strategy take the first 3–4 weeks. Design and system build takes the remaining time.' },
      { question: 'Do we need a brand system before we can do content?', answer: 'Not necessarily. We often run content programs alongside brand work for companies that need to stay active in market while we build the longer-term system.' },
      { question: 'What do we need to have before starting?', answer: 'A clear sense of who your customer is and what problem you solve. We handle everything else.' },
    ],
    ctaHeading: 'Ready to build your brand?',
    ctaBody: 'Tell us where you are and what you\'re trying to accomplish. We\'ll respond within one business day.',
  },

  'how-long-does-a-brand-system-take': {
    heroHeadline: 'How long does a brand system take?',
    seoTitle: 'How long does a brand system take? | Super Conscious',
    heroAnswer: 'Most brand system engagements run 8–12 weeks. The range depends on scope, how quickly your team can review and give feedback, and whether we\'re building from scratch or working from existing brand foundations.',
    body: [
      { _type: 'headingBlock', heading: 'How the time breaks down' },
      { _type: 'paragraphBlock', text: 'Discovery and strategy take the first 3–4 weeks. This is where we learn your market, define your positioning, and write the brief that guides everything that follows. It is the part most studios skip, and the reason most brand work misses.' },
      { _type: 'paragraphBlock', text: 'Design and system build takes the remaining 5–8 weeks. Logo and identity exploration, refinement, application across all brand surfaces, and final documentation. The system deliverable at the end is what your team actually uses.' },
      { _type: 'headingBlock', heading: 'What affects the timeline' },
      { _type: 'paragraphBlock', text: 'Revision cycles are the biggest variable. Engagements with clear decision-making processes move faster than ones where every milestone requires multiple stakeholder rounds. We build review processes that minimize this from the start.' },
      { _type: 'paragraphBlock', text: 'Scope matters too. A brand system for a single product is different from one that needs to work across multiple sub-brands, regions, or audiences. We scope accordingly so there are no surprises midway through.' },
      { _type: 'headingBlock', heading: 'Can the timeline move faster?' },
      { _type: 'paragraphBlock', text: 'Yes, with tradeoffs. If you have a hard deadline, we can compress timelines by running phases in parallel and increasing review frequency. This requires more from your team in a shorter window. Most compressed engagements land at 6–7 weeks.' },
    ],
    processSteps: [
      { label: 'Discovery', description: '2 weeks. Market research, competitive audit, stakeholder interviews.' },
      { label: 'Strategy', description: '2 weeks. Positioning brief, messaging framework, verbal identity.' },
      { label: 'Design', description: '4–6 weeks. Identity exploration, refinement, and application.' },
      { label: 'System', description: '1–2 weeks. Templates, guidelines, and final documentation.' },
    ],
    faqs: [
      { question: 'Can we compress the timeline if we have a deadline?', answer: 'Yes. We can run phases in parallel and increase check-in frequency to compress to 6–7 weeks. It requires faster turnaround on your reviews and a tighter decision-making process on your side.' },
      { question: 'What do we need to do to keep things moving?', answer: 'Designate one decision-maker on your side, give feedback within the agreed review windows, and come to kickoff with a clear brief on your business goals. We handle the rest.' },
      { question: 'Does the timeline include a website redesign?', answer: 'No. Website design and development is scoped separately. Most clients apply their new brand system to the website after the system is complete, or run website work in parallel with a separate timeline.' },
      { question: 'When does the clock start?', answer: 'From kickoff, which we typically schedule 1–2 weeks after contracts are signed to allow for onboarding and scheduling.' },
    ],
    ctaHeading: 'Ready to get started?',
    ctaBody: 'Tell us your timeline and what you need to have in place. We\'ll figure out what\'s realistic and what the right scope is.',
  },

  'brand-system-cost': {
    heroHeadline: 'How much does a brand system cost?',
    seoTitle: 'How much does a brand system cost? | Super Conscious',
    heroAnswer: 'A brand system from a professional studio typically runs $25,000–$80,000 depending on scope. That range reflects the difference between a focused identity system for an early-stage company and a full brand platform for a company operating across multiple markets and teams.',
    body: [
      { _type: 'headingBlock', heading: 'What drives the cost' },
      { _type: 'paragraphBlock', text: 'Scope is the primary driver. A brand system for a single product targeting one audience is a different engagement than one that needs to work across a product suite, multiple buyer types, and a distributed marketing team. More surfaces, more complexity, more cost.' },
      { _type: 'paragraphBlock', text: 'Strategy depth matters too. Studios that include brand strategy, positioning, and verbal identity as part of the system charge more than those delivering visual identity alone. The strategy work is where the leverage is, and skipping it usually means revisiting the design sooner.' },
      { _type: 'headingBlock', heading: 'What you get at each level' },
      { _type: 'paragraphBlock', text: 'At $25,000–$40,000: logo and mark system, color and typography, basic usage guidelines, and core templates. Right for early-stage companies that need a professional identity and a system to use it.' },
      { _type: 'paragraphBlock', text: 'At $40,000–$65,000: everything above plus brand strategy, verbal identity, messaging framework, a broader template set, and a brand guidelines document built for a team. Right for companies that are scaling and need brand to function without a designer in the room.' },
      { _type: 'paragraphBlock', text: 'At $65,000–$80,000 and above: full brand platform work, typically spanning multiple sub-brands or product lines, deeper research, and a system built for enterprise use. Right for companies with complex brand architecture or multiple markets.' },
      { _type: 'headingBlock', heading: 'Why the cheapest option usually costs more' },
      { _type: 'paragraphBlock', text: 'A brand built without strategy gets replaced. We see it regularly: a company spends $8,000 on a logo and guidelines, grows for two years, then needs to redo everything because the brand no longer represents what the business has become. The second engagement always costs more than doing it right the first time.' },
    ],
    processSteps: [
      { label: 'Scoping call', description: 'We learn what you need and define the right scope before quoting.' },
      { label: 'Proposal', description: 'Fixed-fee proposal with clear deliverables, timeline, and payment schedule.' },
      { label: 'Engagement', description: 'Strategy, design, and system build with clear review milestones.' },
      { label: 'Handoff', description: 'Final files, guidelines, and templates delivered and walkthrough completed.' },
    ],
    faqs: [
      { question: 'Do you charge hourly or fixed fee?', answer: 'Fixed fee. We scope each engagement upfront so you know the total cost before we start. We don\'t bill for time, we bill for outcomes.' },
      { question: 'What\'s the payment structure?', answer: 'Typically 50% at kickoff and 50% at final delivery. For larger engagements we can structure milestone-based payments.' },
      { question: 'Is brand strategy included or separate?', answer: 'At Super Conscious, strategy is always included. We don\'t design without it. It\'s built into the scope and the fee.' },
      { question: 'What\'s not included in a brand system engagement?', answer: 'Website design and development, ongoing content production, and paid media are scoped separately. We can run those alongside the brand engagement or introduce you to the right partners.' },
    ],
    ctaHeading: 'Let\'s figure out the right scope.',
    ctaBody: 'Tell us about your business and what you\'re trying to accomplish. We\'ll put together a proposal that fits.',
  },

  'brand-guidelines-vs-brand-system': {
    heroHeadline: 'What\'s the difference between brand guidelines and a brand system?',
    seoTitle: 'Brand Guidelines vs. Brand System | Super Conscious',
    heroAnswer: 'Brand guidelines tell people what to do. A brand system gives them everything they need to do it. Guidelines are a document. A system is the document plus the templates, the components, the logic, and the training that makes consistency possible without a designer in the room.',
    body: [
      { _type: 'headingBlock', heading: 'Why guidelines alone don\'t work' },
      { _type: 'paragraphBlock', text: 'Most brand guidelines fail the moment a non-designer tries to use them. They show the logo rules, the color codes, and the typography stack, but they don\'t show how to actually build a slide deck, a social post, or a one-pager. So teams work around them and the brand drifts.' },
      { _type: 'paragraphBlock', text: 'Guidelines describe what consistency looks like. A system makes consistency achievable. The difference is operational.' },
      { _type: 'headingBlock', heading: 'What a brand system adds' },
      { _type: 'paragraphBlock', text: 'Templates your team can use directly, not just reference. Component libraries for digital surfaces. Writing guides with examples, not just principles. Decision rules for edge cases the guidelines don\'t cover. A system is built for the people who have to execute the brand, not just the designers who created it.' },
      { _type: 'headingBlock', heading: 'When guidelines are enough' },
      { _type: 'paragraphBlock', text: 'If you have an in-house design team that owns all brand production, guidelines may be sufficient. They need the rules, and they have the tools to execute. The system becomes critical when brand execution is distributed across a team of marketers, salespeople, and partners who are not designers.' },
    ],
    processSteps: [
      { label: 'Audit', description: 'We review what you have and identify where the gaps are between guidelines and execution.' },
      { label: 'Strategy', description: 'Positioning and verbal identity defined so the system has something to express.' },
      { label: 'Design', description: 'Visual identity and the rules for how it behaves across every surface.' },
      { label: 'System', description: 'Templates, components, and documentation built for the team doing the work.' },
    ],
    faqs: [
      { question: 'We already have brand guidelines. Do we need a system?', answer: 'It depends on whether your team is actually using them. If you see brand drift across your marketing, the guidelines aren\'t working. A system addresses the execution gap, not just the documentation gap.' },
      { question: 'Can you turn our existing guidelines into a system?', answer: 'Yes. We often do this for companies that have solid visual identity work but need to operationalize it. We audit what exists, identify the gaps, and build the system layer on top.' },
      { question: 'What format does the system come in?', answer: 'Figma files for design components, Google Slides and PowerPoint templates for presentations, a brand guidelines PDF, and a shared drive or Notion setup your team can actually navigate.' },
    ],
    ctaHeading: 'Not sure what you need?',
    ctaBody: 'Send us what you have. We\'ll tell you whether it\'s a guidelines problem or a system problem, and what fixing it looks like.',
  },

  'when-to-invest-in-a-brand-system': {
    heroHeadline: 'When should a company invest in a brand system?',
    seoTitle: 'When to Invest in a Brand System | Super Conscious',
    heroAnswer: 'When inconsistency is costing you something. That might be time: designers and writers recreating the wheel on every project. It might be trust: a brand that looks different across channels signals instability to buyers. Or it might be growth: you are about to hire, raise, or expand and need a brand that scales with you.',
    body: [
      { _type: 'headingBlock', heading: 'The signals that it\'s time' },
      { _type: 'paragraphBlock', text: 'Your marketing looks different across channels and no one can explain why. New team members produce work that doesn\'t feel right and there\'s no way to correct them. You\'re spending design time recreating assets that should already exist. A prospect tells you your brand doesn\'t match the quality of your product.' },
      { _type: 'paragraphBlock', text: 'Any one of these is a sign. All of them together means the brand is actively slowing you down.' },
      { _type: 'headingBlock', heading: 'The inflection points that trigger it' },
      { _type: 'paragraphBlock', text: 'Series A or B funding. Hiring a marketing team. Entering a new market. Launching a second product. Going through a rebrand after an acquisition. These moments all require the business to present itself with more consistency and confidence than a startup identity can support.' },
      { _type: 'headingBlock', heading: 'When it\'s too early' },
      { _type: 'paragraphBlock', text: 'Before product-market fit, a full brand system is usually premature. You don\'t yet know exactly who you are, who you\'re for, or what you stand for, and a brand system built on a moving target becomes obsolete quickly. A simpler identity to get you into market is the right call. Build the system when the business is ready to commit to a position.' },
    ],
    processSteps: [
      { label: 'Readiness check', description: 'We assess whether your business is at the right stage for a full system build.' },
      { label: 'Strategy', description: 'Positioning and messaging defined as the foundation the design builds from.' },
      { label: 'Design', description: 'Identity system built to last the next 3–5 years of company growth.' },
      { label: 'Rollout', description: 'Phased implementation plan so the new brand goes live without disruption.' },
    ],
    faqs: [
      { question: 'We\'re pre-revenue. Is it too early?', answer: 'Probably. Get to customers and product-market fit first. A thoughtful logo and basic visual direction is enough to operate. Save the system build for when you know what you\'re building and who it\'s for.' },
      { question: 'We\'re Series A. Is that the right time?', answer: 'Often yes. Series A is when hiring accelerates, content volume increases, and you need the brand to work without you in the room. It\'s also when you have enough capital to do it properly.' },
      { question: 'Can we invest in the system in phases?', answer: 'Yes. We can prioritize the parts that unblock your team first, then build out the remaining system over subsequent phases.' },
    ],
    ctaHeading: 'Not sure if it\'s the right time?',
    ctaBody: 'Tell us about your company and where you are. We\'ll give you a straight answer on whether a system makes sense right now or what to do first.',
  },

  'what-is-a-verbal-identity': {
    heroHeadline: 'What is a verbal identity?',
    seoTitle: 'What is a verbal identity? | Super Conscious',
    heroAnswer: 'Verbal identity is the written equivalent of a visual identity. It defines how your company sounds: the words you use, the words you avoid, the rhythm of your sentences, and the point of view you bring to everything you publish. Most companies have a visual identity. Very few have a verbal one.',
    body: [
      { _type: 'headingBlock', heading: 'What it includes' },
      { _type: 'paragraphBlock', text: 'A verbal identity covers brand voice (the consistent personality that comes through in everything you write), tone of voice (how that personality adjusts to context, because you talk differently in a sales email than in an error message), a messaging framework (the hierarchy of things you say about your company and products), and a writing guide that gives your team concrete rules to work from.' },
      { _type: 'headingBlock', heading: 'Why most companies skip it' },
      { _type: 'paragraphBlock', text: 'Visual identity is tangible. You can see whether the logo is consistent. You can\'t see inconsistent writing as easily, but you feel it. A company that sounds different depending on who wrote the piece feels smaller than it is, less considered, less trustworthy.' },
      { _type: 'paragraphBlock', text: 'Verbal identity also requires the hardest kind of clarity: knowing what you actually think and how you actually see the world. A lot of companies avoid it because the work of developing a genuine point of view is uncomfortable.' },
      { _type: 'headingBlock', heading: 'What it unlocks' },
      { _type: 'paragraphBlock', text: 'Once you have a verbal identity, content production accelerates. Writers know what they\'re working toward. Briefing gets faster. Review cycles get shorter. And the work that ships is more consistent, because the standard is documented, not just felt.' },
    ],
    processSteps: [
      { label: 'Voice audit', description: 'We read everything you\'ve published and identify what\'s consistent and what\'s noise.' },
      { label: 'Positioning', description: 'We define what your company stands for and how that shapes the way you communicate.' },
      { label: 'Voice system', description: 'Voice, tone, vocabulary rules, and writing principles documented with examples.' },
      { label: 'Messaging framework', description: 'Hierarchy of company messages, from elevator pitch to product-level copy.' },
    ],
    faqs: [
      { question: 'Is verbal identity part of a brand system or separate?', answer: 'At Super Conscious, it\'s always part of the brand system. A visual identity without a verbal identity is half a brand. We build both together.' },
      { question: 'What\'s the difference between brand voice and tone of voice?', answer: 'Voice is consistent. It\'s who you are. Tone is contextual. It\'s how you adjust your voice to the situation. A brand can be consistently direct while being warmer in a welcome email than in a legal notice.' },
      { question: 'How do we get our whole team writing consistently?', answer: 'The writing guide is the tool. It gives concrete examples of what to do and what to avoid, so writers don\'t have to guess. We also offer workshops to walk teams through the system.' },
    ],
    ctaHeading: 'Ready to define how you sound?',
    ctaBody: 'Tell us about your company and what you\'re trying to communicate. We\'ll show you what a verbal identity looks like for a business like yours.',
  },

  'brand-consistency-across-a-team': {
    heroHeadline: 'How do you maintain brand consistency across a team?',
    seoTitle: 'Brand Consistency Across a Team | Super Conscious',
    heroAnswer: 'With a system, not a document. The reason most brand guidelines fail is that they describe what the brand should look like without giving teams the tools to execute it. Consistency comes from templates, components, and clear decision rules — not a PDF that sits in a shared drive.',
    body: [
      { _type: 'headingBlock', heading: 'Why guidelines aren\'t enough' },
      { _type: 'paragraphBlock', text: 'Brand guidelines are written for designers. They show the rules. But most of the people creating branded content at a growing company are not designers: they\'re marketers, salespeople, customer success managers, and executives who need to produce work quickly without breaking the brand.' },
      { _type: 'paragraphBlock', text: 'The gap between what the guidelines say and what the team can actually execute is where brand drift happens. The fix is building tools that close that gap.' },
      { _type: 'headingBlock', heading: 'What actually creates consistency' },
      { _type: 'paragraphBlock', text: 'Templates for every common use case: slide decks, one-pagers, social posts, email signatures, proposals. Components in the tools your team already uses. A writing guide that gives concrete examples, not just principles. And a clear process for getting things reviewed before they go out.' },
      { _type: 'headingBlock', heading: 'The role of training' },
      { _type: 'paragraphBlock', text: 'Even the best system fails without a handoff. When we deliver a brand system, we run a working session with the team to walk through every deliverable and answer questions. The teams that achieve the most consistency are the ones that understand the why behind the rules, not just the rules themselves.' },
    ],
    processSteps: [
      { label: 'Audit', description: 'We look at how your brand is actually being used across your team and identify where consistency breaks down.' },
      { label: 'System build', description: 'Templates, components, and documentation built for the people doing the work.' },
      { label: 'Handoff', description: 'Working session with your team to walk through the system and answer questions.' },
      { label: 'Governance', description: 'A process for reviewing new brand applications and keeping the system up to date.' },
    ],
    faqs: [
      { question: 'Our team is distributed across different cities. Does that make it harder?', answer: 'It\'s actually where a system matters most. Distributed teams can\'t rely on informal knowledge transfer. Everything needs to be documented and accessible.' },
      { question: 'What tools does the system work in?', answer: 'We build for the tools your team actually uses: Figma, Google Slides, PowerPoint, Notion, and Canva where needed. We don\'t deliver assets that require software your team doesn\'t have.' },
      { question: 'How do we keep the system up to date as the company evolves?', answer: 'We build the system with future-proofing in mind and document a governance process for updating it. Most well-built brand systems hold up for 3–5 years before needing significant revision.' },
    ],
    ctaHeading: 'Ready to fix the consistency problem?',
    ctaBody: 'Tell us how big your team is and where the brand is breaking down. We\'ll scope what it takes to fix it.',
  },

  // ── Content Programs ───────────────────────────────────────────────────────

  'what-is-a-content-program': {
    heroHeadline: 'What is a content program?',
    seoTitle: 'What is a content program? | Super Conscious',
    heroAnswer: 'A content program is a structured, ongoing system for producing and distributing content, as opposed to publishing whenever you have something to say. It has a strategy, a cadence, a voice, a set of formats, and a way of measuring whether it\'s working. Publishing is an activity. A program is infrastructure.',
    body: [
      { _type: 'headingBlock', heading: 'What separates a program from just posting' },
      { _type: 'paragraphBlock', text: 'Most companies start content the same way: someone decides to post more, a calendar gets created, and for a few months content goes out. Then it slows down because there is no system behind it, no clear owner, and no way to know whether it\'s doing anything.' },
      { _type: 'paragraphBlock', text: 'A content program solves this by treating content as a function with the same infrastructure as any other business function. Strategy defines what you\'re trying to accomplish and for whom. Operations defines who does what and when. Measurement defines what success looks like and how you track it.' },
      { _type: 'headingBlock', heading: 'What a content program includes' },
      { _type: 'paragraphBlock', text: 'A content strategy with a defined audience, positioning, and point of view. A content calendar with formats and cadences matched to your capacity. A production workflow with clear roles and review processes. A distribution plan for each channel. And a measurement framework tied to business outcomes, not just traffic.' },
      { _type: 'headingBlock', heading: 'When a program is the right investment' },
      { _type: 'paragraphBlock', text: 'When you want content to compound. Single pieces of content have short shelf lives. A program builds a body of work that grows in authority over time, generates inbound consistently, and becomes a competitive asset rather than a line item.' },
    ],
    processSteps: [
      { label: 'Strategy', description: 'Audience, positioning, formats, and channels defined before anything is produced.' },
      { label: 'Pilot', description: 'First 4–6 weeks of content produced, tested, and refined before the full program launches.' },
      { label: 'Operations', description: 'Production workflow, calendar, and team roles set up so the program runs reliably.' },
      { label: 'Measure', description: 'Reporting cadence and metrics defined so you always know what\'s working.' },
    ],
    faqs: [
      { question: 'How is a content program different from a content marketing retainer?', answer: 'A retainer is typically an execution arrangement: someone produces a set number of pieces per month. A program includes strategy, operations, measurement, and execution together. The distinction matters because execution without strategy produces content that doesn\'t compound.' },
      { question: 'How much content does a program produce?', answer: 'It depends on your capacity and goals. A lean program might produce 2–3 pieces per week across one or two channels. A full-scale program might produce daily content across multiple platforms. We scope to what you can sustain and what your audience needs.' },
      { question: 'Do we need to hire a full-time content person to run a program?', answer: 'Not necessarily. We can operate as your content team or as a production partner for an internal team. Many of our clients start with us operating the program and build internal capacity over time.' },
    ],
    ctaHeading: 'Ready to build a program that compounds?',
    ctaBody: 'Tell us about your business and your content goals. We\'ll show you what a program built for your stage looks like.',
  },

  'how-to-build-a-b2b-content-program': {
    heroHeadline: 'How do you build a B2B content program from scratch?',
    seoTitle: 'How to Build a B2B Content Program | Super Conscious',
    heroAnswer: 'Start with your audience and your point of view, not a content calendar. The companies that build programs that last begin with two things: a clear understanding of what their buyers are trying to figure out, and a genuine perspective on the category they operate in. Everything else follows from that.',
    body: [
      { _type: 'headingBlock', heading: 'Step one: define what you actually think' },
      { _type: 'paragraphBlock', text: 'The most common mistake in B2B content is producing content that says nothing distinctive. Category explainers, listicles, and trend roundups are easy to produce and impossible to remember. Before you produce anything, answer this: what does your company believe that most people in your industry don\'t, or won\'t say out loud? That\'s your content foundation.' },
      { _type: 'headingBlock', heading: 'Step two: map your buyer\'s questions' },
      { _type: 'paragraphBlock', text: 'What are your buyers trying to figure out before they hire someone like you? What questions do they ask in first calls? What objections come up? What do they misunderstand about the problem you solve? These questions are your editorial calendar. Write the answers better than anyone else.' },
      { _type: 'headingBlock', heading: 'Step three: pick two formats and one channel' },
      { _type: 'paragraphBlock', text: 'Most B2B content programs fail because they try to be everywhere. Pick one primary channel where your buyers actually spend time and go deep there. Pick two formats you can produce consistently. Quality and consistency on one channel beats mediocrity across five.' },
      { _type: 'headingBlock', heading: 'Step four: build the production machine' },
      { _type: 'paragraphBlock', text: 'Content fails when it depends on the right person being inspired at the right time. Build a production system with a clear workflow, defined roles, a review process, and a calendar that runs several weeks ahead. The goal is to remove the friction that causes programs to stall.' },
    ],
    processSteps: [
      { label: 'Positioning', description: 'Define your audience, your point of view, and the questions only your company can answer.' },
      { label: 'Format and channel selection', description: 'Identify the two formats and one channel to build from first.' },
      { label: 'Editorial calendar', description: 'Build a 12-week calendar of content topics before production starts.' },
      { label: 'Production launch', description: 'First content out the door, reviewed, refined, and published on cadence.' },
    ],
    faqs: [
      { question: 'How long before a B2B content program starts generating leads?', answer: 'Typically 6 months before you see consistent inbound. Search rankings take time to develop. Audience habits take time to form. The companies that quit at month three almost always quit just before things start compounding.' },
      { question: 'Should we do SEO or social first?', answer: 'It depends on your sales cycle. SEO is a longer-term investment that pays compound returns. Social is faster to see engagement but has a shorter content lifespan. For most B2B companies, we recommend a primary focus on one and distribution to the other.' },
      { question: 'What does a realistic starting scope look like?', answer: 'Two long-form pieces per week (blog or LinkedIn), a newsletter that compiles and comments on the best thinking in your category, and a distribution strategy for each. That\'s a program you can operate sustainably.' },
    ],
    ctaHeading: 'Ready to build the program?',
    ctaBody: 'Tell us about your business, your audience, and your goals. We\'ll design a program that fits your stage and your capacity.',
  },

  'content-program-cost': {
    heroHeadline: 'How much does a content program cost?',
    seoTitle: 'How much does a content program cost? | Super Conscious',
    heroAnswer: 'A professionally run B2B content program typically runs $8,000–$25,000 per month depending on volume, formats, and how much of the strategic and editorial work your team handles versus the studio. That range covers everything from a lean weekly program on one channel to a full-scale multi-format operation.',
    body: [
      { _type: 'headingBlock', heading: 'What drives the cost' },
      { _type: 'paragraphBlock', text: 'Volume is the most obvious factor: more content costs more to produce. But the less obvious driver is strategic depth. A program that includes editorial strategy, content briefs, original research, and measurement reporting costs more than one that produces pieces to a brief you\'ve already written. The strategic layer is where most of the leverage is.' },
      { _type: 'paragraphBlock', text: 'Format mix also matters. A program built around written content (blog, newsletter, LinkedIn) is more cost-efficient than one that includes video, audio, or interactive content. We help you choose the formats that deliver the most impact for your audience at your budget.' },
      { _type: 'headingBlock', heading: 'What you get at each level' },
      { _type: 'paragraphBlock', text: 'At $8,000–$12,000 per month: lean program with 2–3 pieces per week, one primary channel, monthly strategy review. Right for companies getting a content program off the ground.' },
      { _type: 'paragraphBlock', text: 'At $12,000–$18,000 per month: full program across 2 channels with editorial strategy, a newsletter, and regular performance reporting. Right for companies ready to treat content as a core growth channel.' },
      { _type: 'paragraphBlock', text: 'At $18,000–$25,000 per month: high-volume program with original research, multiple formats, and full editorial and distribution management. Right for companies where content is a primary business development channel.' },
      { _type: 'headingBlock', heading: 'The build-or-hire question' },
      { _type: 'paragraphBlock', text: 'A full-time senior content strategist and writer costs $120,000–$180,000 in salary alone, before management overhead and tooling. An external program gives you a full team at a comparable or lower cost, with strategic oversight that a single hire can\'t provide. The tradeoff is that the team is shared, not dedicated.' },
    ],
    processSteps: [
      { label: 'Scoping', description: 'We define the right scope based on your goals, capacity, and budget.' },
      { label: 'Strategy', description: 'Editorial strategy built before production starts.' },
      { label: 'Production', description: 'Ongoing content production on an agreed calendar.' },
      { label: 'Reporting', description: 'Monthly performance review and strategy adjustment.' },
    ],
    faqs: [
      { question: 'Is there a minimum engagement length?', answer: 'We typically ask for a 3-month minimum. Content programs take time to ramp and it\'s difficult to evaluate performance in less than a quarter.' },
      { question: 'What\'s included in the monthly fee?', answer: 'Strategy, content production, editing, and light distribution support. Tools, paid promotion, and design production beyond standard brand templates are scoped separately.' },
      { question: 'Can we start small and scale up?', answer: 'Yes. Most clients start with a lean program and expand scope once the foundation is working. We design programs to scale.' },
    ],
    ctaHeading: 'Let\'s figure out the right scope.',
    ctaBody: 'Tell us about your goals and what you can commit to. We\'ll put together a program that fits.',
  },

  'how-long-until-content-marketing-works': {
    heroHeadline: 'How long does it take for content marketing to work?',
    seoTitle: 'How Long Until Content Marketing Works | Super Conscious',
    heroAnswer: 'Six months before you see compounding returns, twelve before the program is self-sustaining. Content works through accumulation. Each piece builds on the last, search rankings take time to develop, and audiences take time to form habits. The companies that quit at month three almost always quit just before things start working.',
    body: [
      { _type: 'headingBlock', heading: 'What happens in the first 90 days' },
      { _type: 'paragraphBlock', text: 'You build the foundation. You define your positioning, your voice, your formats, and your production workflow. You publish consistently. Traffic is low. Engagement is modest. This is not failure, it is infrastructure. The mistake is treating this phase as the test of whether content works.' },
      { _type: 'headingBlock', heading: 'What happens between months 3 and 6' },
      { _type: 'paragraphBlock', text: 'Search rankings begin to develop. A small number of pieces start driving consistent traffic. Your audience begins to form habits around your publishing schedule. You start to see which topics and formats resonate. The program becomes easier to operate because you\'ve learned what your audience responds to.' },
      { _type: 'headingBlock', heading: 'What happens after 6 months' },
      { _type: 'paragraphBlock', text: 'The program starts compounding. High-performing pieces continue to drive traffic without additional production cost. Your brand becomes associated with the topics you\'ve covered consistently. Inbound inquiries from content start to appear in your pipeline. The body of work you\'ve built becomes a business asset.' },
      { _type: 'headingBlock', heading: 'What accelerates the timeline' },
      { _type: 'paragraphBlock', text: 'Distribution. Content that gets shared by people with existing audiences reaches critical mass faster. A founder or executive with a personal following can dramatically accelerate a program. Original research and strong points of view generate more sharing than informational content alone.' },
    ],
    processSteps: [
      { label: 'Foundation', description: 'Strategy, voice, formats, and production workflow established in weeks 1–4.' },
      { label: 'Build', description: 'Consistent publishing through months 1–3, establishing the pattern and testing formats.' },
      { label: 'Compound', description: 'Months 4–6, where search rankings develop and audience habits form.' },
      { label: 'Optimize', description: 'From month 6 onward, doubling down on what works and expanding from a position of evidence.' },
    ],
    faqs: [
      { question: 'How do we measure progress before we see results?', answer: 'Leading indicators: publishing consistency, content quality scores, early engagement rates. These tell you whether the program is working before lagging indicators like traffic and pipeline materialize.' },
      { question: 'Can paid amplification speed things up?', answer: 'It can accelerate distribution, but it doesn\'t replace organic compounding. Paid promotion of strong organic content can help seed an audience. Paid promotion of weak content just burns budget.' },
      { question: 'What if we need results faster than 6 months?', answer: 'Content is not the right channel for immediate pipeline. If you need leads in 60 days, outbound or paid acquisition will serve you better. Content is a compound investment, not a quick lever.' },
    ],
    ctaHeading: 'Ready to commit to the long game?',
    ctaBody: 'Tell us about your goals and your timeline. We\'ll design a program that builds the right foundation and show you how to measure progress along the way.',
  },

  'what-is-a-thought-leadership-program': {
    heroHeadline: 'What is a thought leadership program?',
    seoTitle: 'What is a thought leadership program? | Super Conscious',
    heroAnswer: 'A thought leadership program is a structured effort to build a company or founder\'s reputation as a serious voice in their category. It combines original points of view, consistent publishing, and strategic distribution to make sure the right people are reading and sharing your thinking. It is different from content marketing. The goal is credibility, not traffic.',
    body: [
      { _type: 'headingBlock', heading: 'Content marketing vs. thought leadership' },
      { _type: 'paragraphBlock', text: 'Content marketing is designed to be found. It answers questions people are searching for, drives traffic, and converts readers into leads. Thought leadership is designed to be remembered. It builds the kind of reputation that makes buyers think of you first when they\'re ready to hire, even if they\'ve never searched for you.' },
      { _type: 'paragraphBlock', text: 'The best programs do both. But the thinking and the measurement are different, and mixing them up is why most thought leadership programs produce neither credibility nor traffic.' },
      { _type: 'headingBlock', heading: 'What a program actually includes' },
      { _type: 'paragraphBlock', text: 'A defined point of view and editorial calendar built around it. A publishing rhythm your audience can count on. Long-form writing that shows original thinking, not summaries of what everyone else is saying. Distribution into the communities, publications, and inboxes where your buyers spend time. And a speaker or media strategy for founders who want to build personal reputation alongside the company brand.' },
      { _type: 'headingBlock', heading: 'Who it\'s right for' },
      { _type: 'paragraphBlock', text: 'Companies that sell complex, high-value services where trust is the primary buying criterion. Founders who want to become known voices in their category. Companies entering a crowded market and competing on perspective rather than price. It is not right for companies that don\'t have a genuine point of view, or that want results in 60 days.' },
    ],
    processSteps: [
      { label: 'POV development', description: 'We identify and articulate the perspective that sets your thinking apart in your category.' },
      { label: 'Editorial calendar', description: 'A 12-month calendar of topics built from your POV and your buyers\' questions.' },
      { label: 'Content production', description: 'Long-form pieces produced on cadence, reviewed for originality and depth.' },
      { label: 'Distribution', description: 'Strategic placement in newsletters, publications, and communities where your buyers are.' },
    ],
    faqs: [
      { question: 'How long before thought leadership builds credibility?', answer: 'Expect 6–12 months before the program has a measurable effect on your reputation. Credibility accrues slowly and compounds over time. The floor is commitment to a 12-month program.' },
      { question: 'Does the content need to come from the founder?', answer: 'Not necessarily. Thought leadership can be attributed to the company or to a team of subject matter experts. Founder-attributed content tends to build faster because people follow people more readily than they follow brands.' },
      { question: 'What makes thought leadership actually work?', answer: 'Having something original to say. Programs that produce summaries, roundups, and safe observations do not build reputations. The content needs to take a position, challenge assumptions, or share insights that readers can\'t get elsewhere.' },
    ],
    ctaHeading: 'Ready to build a reputation in your category?',
    ctaBody: 'Tell us what you believe and who you\'re trying to reach. We\'ll build the program that gets you there.',
  },

  'how-to-measure-a-content-program': {
    heroHeadline: 'How do you measure a content program?',
    seoTitle: 'How do you measure a content program? | Super Conscious',
    heroAnswer: 'With a mix of leading and lagging indicators. Traffic and rankings tell you the program is building reach. Pipeline influence and sourced revenue tell you it is driving business. The mistake most companies make is measuring content only by what is easy to track — pageviews — and missing the slower-moving signals that indicate the program is actually working.',
    body: [
      { _type: 'headingBlock', heading: 'Leading indicators' },
      { _type: 'paragraphBlock', text: 'Publishing consistency: are you hitting your cadence? Content quality: are pieces meeting your editorial standard before they go out? Engagement rates: are readers spending time with the content and sharing it? Search ranking trajectories: are target keywords moving in the right direction? These tell you the program is being operated correctly before results materialize.' },
      { _type: 'headingBlock', heading: 'Lagging indicators' },
      { _type: 'paragraphBlock', text: 'Organic traffic growth. Newsletter subscriber growth. Inbound leads that reference your content. Pipeline that was influenced by content before close. Revenue sourced from content-driven inbound. These are the outcomes, but they take time to develop. A program that scores well on leading indicators and poorly on lagging ones is on the right track. A program that scores poorly on both has a strategy problem.' },
      { _type: 'headingBlock', heading: 'What not to measure' },
      { _type: 'paragraphBlock', text: 'Vanity metrics: total pageviews without context, social likes, and follower counts that don\'t correlate with business outcomes. These are easy to produce and easy to report but tell you nothing about whether content is doing what it\'s supposed to do.' },
      { _type: 'headingBlock', heading: 'The measurement cadence' },
      { _type: 'paragraphBlock', text: 'Monthly: review publishing consistency, engagement rates, and top-performing pieces. Quarterly: review traffic trends, ranking progress, and pipeline influence. Annually: evaluate whether the program\'s strategic direction is producing the right business outcomes.' },
    ],
    processSteps: [
      { label: 'Baseline', description: 'Establish current traffic, rankings, and pipeline metrics before the program starts.' },
      { label: 'Define metrics', description: 'Agree on the leading and lagging indicators that map to your business goals.' },
      { label: 'Monthly reporting', description: 'Performance review against targets with clear recommended actions.' },
      { label: 'Quarterly strategy review', description: 'Deeper review of what\'s working and what needs to change in the program.' },
    ],
    faqs: [
      { question: 'How do we attribute revenue to content?', answer: 'We use UTM tracking, CRM tagging, and first-touch/last-touch attribution to understand how content influences pipeline. Perfect attribution is not possible, but good-enough attribution is achievable with the right setup.' },
      { question: 'What\'s a realistic growth target for organic traffic?', answer: 'For a well-run B2B content program starting from near zero, 20–40% quarter-over-quarter growth in organic traffic is achievable in the first year. The trajectory matters more than the absolute number in the early months.' },
      { question: 'When should we add more content if the program isn\'t growing?', answer: 'Adding volume to a program that isn\'t working rarely helps. More often the issue is strategic: the content is not addressing the right audience, taking a distinctive enough point of view, or being distributed in the right places. Fix the strategy before increasing the volume.' },
    ],
    ctaHeading: 'Want a program you can actually measure?',
    ctaBody: 'Tell us what outcomes you\'re trying to drive. We\'ll build a program with measurement built in from day one.',
  },

  // ── Digital Products ───────────────────────────────────────────────────────

  'what-does-a-digital-product-design-engagement-include': {
    heroHeadline: 'What does a digital product design engagement include?',
    seoTitle: 'What a Product Design Engagement Includes | Super Conscious',
    heroAnswer: 'A digital product design engagement typically covers user research, interaction design, visual design, and a design system: the components and patterns that allow your engineering team to build consistently without returning to design for every screen. The scope depends on whether you are building from scratch or working from an existing product.',
    body: [
      { _type: 'headingBlock', heading: 'Research and definition' },
      { _type: 'paragraphBlock', text: 'The work starts before any design happens. We map the problem space: who the users are, what they\'re trying to accomplish, where current solutions fail them, and what success looks like. This is the work that prevents expensive redesigns six months after launch.' },
      { _type: 'headingBlock', heading: 'Interaction design' },
      { _type: 'paragraphBlock', text: 'How the product works: flows, states, navigation, error handling, and the logic of how users move through the experience. This is typically done in wireframes or low-fidelity prototypes before any visual design is applied, so we\'re solving structural problems before aesthetic ones.' },
      { _type: 'headingBlock', heading: 'Visual design' },
      { _type: 'paragraphBlock', text: 'The finished look and feel of the product: color, typography, iconography, and visual hierarchy applied to every screen. For companies with an existing brand system, we build from it. For companies without one, we establish a product visual language as part of the engagement.' },
      { _type: 'headingBlock', heading: 'Design system' },
      { _type: 'paragraphBlock', text: 'A library of components, patterns, and documentation that allows engineers to build consistently and allows design to scale without redesigning common elements. The design system is what makes the engagement sustainable: it\'s how the product stays coherent as it grows.' },
    ],
    processSteps: [
      { label: 'Discovery', description: 'User research, stakeholder interviews, and problem definition.' },
      { label: 'Architecture', description: 'Information architecture, user flows, and interaction design.' },
      { label: 'Design', description: 'Visual design applied to all screens and states.' },
      { label: 'System', description: 'Component library and documentation handed off to engineering.' },
    ],
    faqs: [
      { question: 'Do you do development as well as design?', answer: 'We focus on design. We work closely with your engineering team or can recommend development partners for the build.' },
      { question: 'What format are the design files delivered in?', answer: 'Figma. We build component libraries, auto-layout systems, and documentation in Figma and hand off to engineering with full specs.' },
      { question: 'Do you work with existing products or only greenfield?', answer: 'Both. Many of our engagements are redesigns or feature additions to existing products. We start with an audit of what exists before designing anything new.' },
      { question: 'How do you work with our engineering team?', answer: 'We build in public: engineering is included in design reviews from the start, not just handed specs at the end. This reduces implementation surprises and catches feasibility issues early.' },
    ],
    ctaHeading: 'Ready to design something worth building?',
    ctaBody: 'Tell us about your product and where you are in the process. We\'ll scope what the right engagement looks like.',
  },

  'how-much-does-product-design-cost': {
    heroHeadline: 'How much does product design cost?',
    seoTitle: 'How much does product design cost? | Super Conscious',
    heroAnswer: 'A focused product design engagement typically runs $40,000–$150,000 depending on scope and duration. That range covers a 6–8 week sprint to design a core user flow at the low end, and a 4–6 month engagement covering research, full product design, and a design system at the high end.',
    body: [
      { _type: 'headingBlock', heading: 'What drives the cost' },
      { _type: 'paragraphBlock', text: 'Scope and duration are the primary drivers. Designing one flow for one user type is a smaller engagement than designing an entire product for three user types with different permissions and goals. Research depth matters too: engagements that include user interviews, usability testing, and synthesis cost more than those where the product team has already defined the problem.' },
      { _type: 'headingBlock', heading: 'What you get at each level' },
      { _type: 'paragraphBlock', text: 'At $40,000–$60,000: a focused sprint covering 1–2 core user flows, delivered in 6–8 weeks. Right for companies that have a specific problem to solve and a clear brief.' },
      { _type: 'paragraphBlock', text: 'At $60,000–$100,000: full product design engagement covering research, flows, visual design, and a component library. 10–16 weeks. Right for companies building or redesigning a core product.' },
      { _type: 'paragraphBlock', text: 'At $100,000–$150,000: extended engagement with deeper research, complex product architecture, and a full design system. Right for products with multiple user types, complex workflows, or enterprise requirements.' },
      { _type: 'headingBlock', heading: 'Build or hire?' },
      { _type: 'paragraphBlock', text: 'A senior product designer runs $130,000–$180,000 per year. For a contained engagement, a studio is more cost-efficient. For ongoing product development, an in-house designer who knows the product deeply makes more sense. Many companies work with a studio for the initial build and hire internally once the product is established.' },
    ],
    processSteps: [
      { label: 'Scope definition', description: 'We define the right engagement size before quoting.' },
      { label: 'Research', description: 'User research and problem definition proportional to the scope.' },
      { label: 'Design', description: 'Flows, screens, and system built to the defined brief.' },
      { label: 'Handoff', description: 'Figma files, specs, and design system documentation delivered.' },
    ],
    faqs: [
      { question: 'Is there a discovery phase before committing to full scope?', answer: 'Often yes. For larger engagements, we can scope a 2–3 week discovery phase to define the problem and validate scope before committing to the full engagement.' },
      { question: 'Do you charge hourly or fixed fee?', answer: 'Fixed fee. We scope each engagement upfront so you know the cost before we start.' },
      { question: 'What\'s not included in the design fee?', answer: 'Development, user recruitment for research, and licensed stock assets. We can manage user recruitment as an add-on.' },
    ],
    ctaHeading: 'Let\'s scope your engagement.',
    ctaBody: 'Tell us what you\'re building and where you are. We\'ll put together a proposal with a clear scope and fee.',
  },

  'how-long-to-design-a-web-app': {
    heroHeadline: 'How long does it take to design a web app?',
    seoTitle: 'How long does it take to design a web app? | Super Conscious',
    heroAnswer: 'A focused web application design engagement typically runs 8–16 weeks. The range depends on complexity: how many user types, how many core flows, and whether the engagement includes a design system or just the screens. Research and definition take the first 3–4 weeks. Design and iteration take the rest.',
    body: [
      { _type: 'headingBlock', heading: 'What affects the timeline' },
      { _type: 'paragraphBlock', text: 'Complexity is the main driver. A web app with one user type, three core flows, and a well-defined brief can be designed in 8 weeks. An app with multiple user types, complex permissions, and admin interfaces alongside user-facing screens needs 12–16 weeks.' },
      { _type: 'paragraphBlock', text: 'Research depth also matters. If you have clear user research and a validated problem definition, we can move faster. If we need to do discovery work to define the problem before designing the solution, that adds 2–3 weeks.' },
      { _type: 'headingBlock', heading: 'How the time breaks down' },
      { _type: 'paragraphBlock', text: 'Weeks 1–3: discovery and definition. User research, stakeholder alignment, problem framing, and information architecture. Weeks 4–8: interaction design. Flows, wireframes, and prototypes before visual design is applied. Weeks 8–14: visual design. Finished screens, states, and edge cases. Final 2 weeks: design system and handoff documentation.' },
      { _type: 'headingBlock', heading: 'What slows things down' },
      { _type: 'paragraphBlock', text: 'Unclear ownership on the client side. When multiple stakeholders need to approve each review, cycles lengthen significantly. Scope changes mid-engagement. Feedback that contradicts earlier decisions. We build review processes that minimize these risks, but the biggest factor is having a clear decision-maker on your team.' },
    ],
    processSteps: [
      { label: 'Discovery', description: '2–3 weeks. Research, problem definition, and architecture.' },
      { label: 'Interaction design', description: '3–4 weeks. Flows, wireframes, and prototypes.' },
      { label: 'Visual design', description: '4–6 weeks. Finished screens, states, and system.' },
      { label: 'Handoff', description: '1–2 weeks. Figma files, specs, and documentation.' },
    ],
    faqs: [
      { question: 'Can we compress the timeline if we have a launch date?', answer: 'Yes, with tradeoffs. Parallel tracks can compress the timeline by 20–30%. It requires faster review turnaround and a dedicated decision-maker on your side.' },
      { question: 'Do you design for mobile as well as desktop?', answer: 'Yes. We design responsive layouts for web apps and can scope native mobile alongside or separately.' },
      { question: 'When should engineering be involved?', answer: 'From the start. We include engineering in design reviews from week one, not just at handoff. It catches feasibility issues early and produces better results.' },
    ],
    ctaHeading: 'Ready to start?',
    ctaBody: 'Tell us what you\'re building and when you need it. We\'ll scope what\'s realistic and what it takes to get there.',
  },

  'design-system-vs-brand-system': {
    heroHeadline: 'What\'s the difference between a design system and a brand system?',
    seoTitle: 'Design System vs. Brand System | Super Conscious',
    heroAnswer: 'A brand system covers how your company presents itself across every surface: visual identity, voice, messaging, and guidelines for print, digital, and everything in between. A design system is specifically for digital product development — the components, tokens, and patterns your engineering team uses to build consistent interfaces. Brand systems inform design systems. They are not the same thing.',
    body: [
      { _type: 'headingBlock', heading: 'What a brand system covers' },
      { _type: 'paragraphBlock', text: 'A brand system defines the visual and verbal identity of a company: the logo, color palette, typography, photography style, voice, messaging framework, and guidelines for how these elements work together across all brand touchpoints. It\'s built for the whole company — marketing, sales, product, communications — and works across print, digital, and physical surfaces.' },
      { _type: 'headingBlock', heading: 'What a design system covers' },
      { _type: 'paragraphBlock', text: 'A design system is a library of UI components — buttons, forms, navigation patterns, tables, modals — along with the design tokens (colors, spacing, typography values) that define how those components look. It\'s built specifically for product teams and lives in tools like Figma and code repositories. Its purpose is to help engineers and designers build digital interfaces consistently and efficiently.' },
      { _type: 'headingBlock', heading: 'How they relate' },
      { _type: 'paragraphBlock', text: 'A brand system should inform a design system. The color tokens in your design system should come from your brand color palette. The typography choices should reflect your brand typefaces. The visual style of your UI components should be consistent with your overall brand identity.' },
      { _type: 'paragraphBlock', text: 'But a design system goes further than a brand system in product-specific directions: interaction patterns, accessibility requirements, responsive behavior, dark mode variants. It solves problems that don\'t exist in a brand system.' },
      { _type: 'headingBlock', heading: 'Which one do you need?' },
      { _type: 'paragraphBlock', text: 'If you\'re building a marketing site, a sales deck, or a content program: brand system. If you\'re building a web or mobile application with an engineering team: design system, informed by your brand system. If you have neither and you\'re building a product company: brand system first, design system when you have an engineering team that needs it.' },
    ],
    processSteps: [
      { label: 'Brand system', description: 'Visual identity, voice, and guidelines for the whole company.' },
      { label: 'Brand to product', description: 'Translating brand tokens into product-ready design values.' },
      { label: 'Component library', description: 'UI components built from brand foundations, ready for engineering.' },
      { label: 'Documentation', description: 'Guidelines for both marketing teams (brand) and product teams (design system).' },
    ],
    faqs: [
      { question: 'Can we have a design system without a brand system?', answer: 'Yes, but the design system will lack a foundation. Components built without a defined brand identity tend to drift visually over time and don\'t reflect a coherent visual language.' },
      { question: 'We have a brand system but no design system. Where do we start?', answer: 'Extract the design tokens from your brand system: colors, typography, spacing. Use those as the foundation for your component library. We can do this translation work as part of a product design engagement.' },
      { question: 'Do you build design systems in code or just in Figma?', answer: 'We deliver design systems in Figma with full specifications for engineering. Code implementation is typically handled by your engineering team, though we can manage that separately.' },
    ],
    ctaHeading: 'Not sure which one you need?',
    ctaBody: 'Tell us what you\'re building. We\'ll tell you what system to build first and what the right scope looks like.',
  },

  'what-to-look-for-in-a-product-design-studio': {
    heroHeadline: 'What should you look for in a product design studio?',
    seoTitle: 'Choosing a Product Design Studio | Super Conscious',
    heroAnswer: 'Work that shows strategic thinking, not just craft. Any studio can produce good-looking screens. The ones worth hiring can show you why they made the decisions they made — how they identified the right problem to solve, how they tested their assumptions, and how the design performed after it shipped.',
    body: [
      { _type: 'headingBlock', heading: 'The case studies tell you everything' },
      { _type: 'paragraphBlock', text: 'Look for studios that can articulate the problem before showing you the solution. If a case study starts with "the challenge was to make the UI more modern," that\'s a signal they are solving aesthetic problems. If it starts with "users were abandoning the checkout flow at step 3 because of X," that\'s a signal they are solving business problems.' },
      { _type: 'headingBlock', heading: 'Ask about decisions, not deliverables' },
      { _type: 'paragraphBlock', text: 'In the initial conversation, ask them about a decision they made in a past project that turned out to be wrong, and what they did about it. Ask what they pushed back on with a client and why. Ask how they handle disagreement between engineering and design. The answers reveal whether you\'re hiring a partner or a vendor.' },
      { _type: 'headingBlock', heading: 'Look for process, not just portfolio' },
      { _type: 'paragraphBlock', text: 'A studio with strong work and unclear process is hard to work with and hard to predict. You want to understand: how do they run discovery? How do they make decisions? How do they include engineering? How do they handle scope changes? A clear process is a sign of a mature studio.' },
      { _type: 'headingBlock', heading: 'Red flags' },
      { _type: 'paragraphBlock', text: 'No design system in the deliverables. Case studies that show only final screens with no process artifacts. Proposals that jump to deliverables without asking about the problem. Portfolios that all look the same regardless of client or context. Reluctance to share references.' },
    ],
    processSteps: [
      { label: 'Portfolio review', description: 'Evaluate case studies for strategic depth, not just visual quality.' },
      { label: 'Intro call', description: 'Ask about process, decisions, and how they handle disagreement.' },
      { label: 'Reference check', description: 'Talk to past clients about what working with the studio was actually like.' },
      { label: 'Proposal review', description: 'Evaluate whether the proposal reflects understanding of your problem.' },
    ],
    faqs: [
      { question: 'How many studios should we evaluate?', answer: 'Two or three. Evaluating more than that usually produces paralysis rather than a better decision. Get to a short list quickly and go deep on each.' },
      { question: 'Should we run a paid design exercise?', answer: 'Optionally, and only if it\'s reasonable in scope. A small paid exercise shows you how the studio thinks and how they communicate. An unpaid exercise that requires significant work is not reasonable to ask for.' },
      { question: 'What should we have ready before reaching out to studios?', answer: 'A brief that describes the product, the users, the problem you\'re trying to solve, and your timeline and budget. You don\'t need a full spec, but studios can\'t scope effectively without the basics.' },
    ],
    ctaHeading: 'Evaluating studios right now?',
    ctaBody: 'Tell us about your product and what you\'re trying to build. We\'ll give you a straight assessment of whether we\'re the right fit.',
  },

  // ── Cross-vertical ─────────────────────────────────────────────────────────

  'brand-or-content-first': {
    heroHeadline: 'What comes first: brand or content?',
    seoTitle: 'What comes first: brand or content? | Super Conscious',
    heroAnswer: 'Brand. But the real answer depends on where you are. If you are still figuring out your positioning and voice, producing content before your brand is set means building something you will eventually redo. If you have a clear point of view and need to stay in market, content can start while brand is being built, as long as both are moving.',
    body: [
      { _type: 'headingBlock', heading: 'Why brand comes first' },
      { _type: 'paragraphBlock', text: 'A content program needs something to say. Brand strategy gives you that: your positioning, your voice, your point of view. Without it, content becomes reactive. You publish what feels right in the moment instead of building a body of work that compounds.' },
      { _type: 'paragraphBlock', text: 'The companies that skip brand and go straight to content usually end up with 12 months of posts that no longer represent who they are. Starting with brand means the content you build in year one is still usable in year three.' },
      { _type: 'headingBlock', heading: 'When to run them in parallel' },
      { _type: 'paragraphBlock', text: 'For companies already in market that cannot go dark while brand is built, we often run content and brand work at the same time. The first 6–8 weeks of content stay in safe territory: founder perspective, point of view pieces, observations that hold up regardless of how the visual identity lands.' },
      { _type: 'paragraphBlock', text: 'Once brand is set, we apply it to everything and the content program shifts into a higher gear. The parallel approach adds a few weeks to the overall timeline but means you never go quiet.' },
      { _type: 'headingBlock', heading: 'What breaks when you get it backwards' },
      { _type: 'paragraphBlock', text: 'The most common version we see: a company builds an audience through content, then rebrands. The new identity does not match the voice people followed. Reconciling that takes longer than building it right the first time.' },
    ],
    processSteps: [
      { label: 'Brand strategy', description: 'Positioning, voice, and messaging framework established before any content goes out.' },
      { label: 'Content pilot', description: 'First 4–6 weeks of content produced against the new brand to test the voice and build the muscle.' },
      { label: 'System build', description: 'Templates, guidelines, and briefs so your team can execute without reinventing the approach each time.' },
      { label: 'Program', description: 'Ongoing content program running on a brand foundation that scales with you.' },
    ],
    faqs: [
      { question: 'Can we start content before our brand is finished?', answer: 'Yes, with guardrails. Thought leadership, founder perspective, and category-level content are safe to start early. Product marketing and campaign work should wait until brand is set.' },
      { question: 'We already have content. Do we have to redo it all after a rebrand?', answer: 'Not necessarily. Good brand strategy should be additive. We audit what holds up and what needs to change, so you are not starting from scratch.' },
      { question: 'How long does brand strategy take before we can start content?', answer: 'Brand strategy typically takes 3–4 weeks. You can start content planning in parallel and begin publishing 2–3 weeks after strategy is complete.' },
      { question: 'Do you do both brand and content, or just one?', answer: 'Both. Super Conscious runs brand systems and content programs, often together. That is what makes the parallel approach work: one team holds both.' },
    ],
    ctaHeading: 'Not sure where to start?',
    ctaBody: 'Tell us where you are. We will tell you whether to start with brand, content, or both, and what that looks like in practice.',
  },

  'do-i-need-a-brand-system-before-content': {
    heroHeadline: 'Do you need a brand system before you start content marketing?',
    seoTitle: 'Brand System Before Content Marketing? | Super Conscious',
    heroAnswer: 'Not a full system, but you need something to work from. Content produced without a defined voice or point of view tends to be inconsistent, and inconsistency erodes trust faster than silence. You do not need a complete brand system before your first piece. You do need to know what you stand for, who you are talking to, and how you want to sound.',
    body: [
      { _type: 'headingBlock', heading: 'What you actually need before starting content' },
      { _type: 'paragraphBlock', text: 'A positioning statement: who you are, who you\'re for, and what makes you different. A voice definition: not a full verbal identity, but enough to make decisions about how to write. A point of view on your category: what you believe that most people in your space won\'t say. These three things let you produce content that builds on itself rather than contradicting itself.' },
      { _type: 'headingBlock', heading: 'What happens when you skip it' },
      { _type: 'paragraphBlock', text: 'The writing sounds like whoever produced it that week. Tone shifts between pieces. The company\'s position in the market is unclear. Early content becomes a liability when you rebrand because it reflects a version of the company that no longer exists.' },
      { _type: 'headingBlock', heading: 'The minimum viable brand for content' },
      { _type: 'paragraphBlock', text: 'Before starting a content program, we typically run a 2-week brand foundations sprint that defines positioning, voice, and messaging hierarchy. This is lighter than a full brand system but gives content the foundation it needs. It also becomes the brief for the full brand system when you\'re ready to build one.' },
    ],
    processSteps: [
      { label: 'Brand foundations', description: 'Positioning, voice, and messaging hierarchy defined in 2 weeks.' },
      { label: 'Content pilot', description: 'First content produced against the foundations to validate the direction.' },
      { label: 'Full brand system', description: 'Complete brand system built when the business is ready to scale.' },
      { label: 'Content program', description: 'Full program launched on a brand foundation that supports it.' },
    ],
    faqs: [
      { question: 'Can you run brand foundations and content at the same time?', answer: 'Yes. We often run a 2-week brand foundations sprint and start content production in week 3. By the time the first pieces go out, the brand direction is established.' },
      { question: 'What\'s the difference between brand foundations and a full brand system?', answer: 'Brand foundations cover strategy and verbal identity: positioning, voice, and messaging. A full brand system adds visual identity, design, templates, and documentation. Foundations give you the strategic layer. The system operationalizes it across the whole company.' },
      { question: 'We have a logo and a style guide. Is that enough?', answer: 'It\'s a start for visuals. For content, you also need a voice definition and a point of view. Most style guides don\'t include those. We can add them quickly without rebuilding what you have.' },
    ],
    ctaHeading: 'Ready to get the foundation right?',
    ctaBody: 'Tell us where you are with brand and content. We\'ll tell you the fastest path to producing content that compounds.',
  },

  'creative-studio-vs-freelancer': {
    heroHeadline: 'Creative studio versus freelancer: which is right for you?',
    seoTitle: 'Creative Studio vs. Freelancer | Super Conscious',
    heroAnswer: 'It depends on scope and how much coordination you want to manage. Freelancers are right for contained, well-defined projects where you know exactly what you need. A studio makes sense when the work requires multiple disciplines working together — strategy, design, writing, and production — and when you want a single team accountable for the outcome.',
    body: [
      { _type: 'headingBlock', heading: 'When a freelancer is the right call' },
      { _type: 'paragraphBlock', text: 'You have a specific, well-defined task: design five social templates, write a series of blog posts, produce a video. You have a tight budget and can do the project management yourself. You have the expertise to brief and review the work. In these situations, a freelancer is more cost-efficient and easier to engage.' },
      { _type: 'headingBlock', heading: 'When a studio is the right call' },
      { _type: 'paragraphBlock', text: 'The work requires multiple disciplines that need to work together: a brand system needs strategy, design, and writing. A content program needs editorial direction, writing, and distribution strategy. Managing multiple freelancers across these disciplines requires expertise and time that most marketing teams don\'t have.' },
      { _type: 'paragraphBlock', text: 'A studio also brings continuity. The team that builds your brand system is the same team that builds your content program and understands how your brand voice should work in practice. Freelancers have to be re-onboarded for each project.' },
      { _type: 'headingBlock', heading: 'The cost comparison' },
      { _type: 'paragraphBlock', text: 'Freelancers are often cheaper per hour, but the fully-loaded cost of managing multiple freelancers across a complex project — your time, coordination overhead, re-briefing, inconsistency — often closes the gap. For contained work, the math favors freelancers. For complex, multi-disciplinary programs, the math often favors a studio.' },
    ],
    processSteps: [
      { label: 'Scope assessment', description: 'Define what you need and how complex the coordination is.' },
      { label: 'Budget reality check', description: 'Compare the true cost of freelancer management vs. studio engagement.' },
      { label: 'Decision', description: 'Right model for the work and your team\'s capacity to manage it.' },
      { label: 'Engagement', description: 'Clear brief, clear deliverables, and a review process that works for both sides.' },
    ],
    faqs: [
      { question: 'Can we use freelancers for some things and a studio for others?', answer: 'Yes, and many companies do. Use a studio for the strategic and systems work that requires continuity, and freelancers for execution tasks where the brief is already clear.' },
      { question: 'What makes Super Conscious different from other studios?', answer: 'We operate as a production studio, not a strategy consultancy. We build things and ship them, not just recommend. And we work across brand, content, and product, so the disciplines talk to each other.' },
      { question: 'How do we evaluate whether a studio is worth the premium?', answer: 'Look at the work, not the pitch. Ask about projects that did not go as planned and what they did about it. Check references. The premium is justified when the studio brings thinking that changes the outcome, not just execution that delivers to your brief.' },
    ],
    ctaHeading: 'Not sure which is right for your project?',
    ctaBody: 'Tell us what you\'re trying to do. We\'ll give you a straight answer on whether we\'re the right fit or whether a different model makes more sense.',
  },

  'what-to-ask-a-creative-agency': {
    heroHeadline: 'What should you ask a creative agency before hiring them?',
    seoTitle: 'What to Ask a Creative Agency | Super Conscious',
    heroAnswer: 'The questions that matter most are not about process or credentials — they are about how the agency thinks. What do they believe that most agencies do not? How do they handle disagreement with a client? Can they show you work that did not go as planned and what they learned? The answers reveal whether you are hiring a vendor or a partner.',
    body: [
      { _type: 'headingBlock', heading: 'Questions about thinking' },
      { _type: 'paragraphBlock', text: '"What do you believe about brand (or content, or design) that most agencies don\'t?" If they can\'t answer this, they don\'t have a point of view. You want to work with people who think about the work, not just execute it.' },
      { _type: 'paragraphBlock', text: '"Tell me about a project that didn\'t go as planned. What happened and what did you do?" This tells you more about the agency than any case study. How they handle difficulty is what you\'ll experience when your project gets difficult.' },
      { _type: 'headingBlock', heading: 'Questions about working style' },
      { _type: 'paragraphBlock', text: '"How do you handle disagreement with a client?" You want a studio that pushes back when they think you\'re wrong, not one that does whatever you say. The former produces better work. The latter produces expensive mistakes.' },
      { _type: 'paragraphBlock', text: '"Who is our day-to-day contact and how involved are the senior people?" Many agencies pitch with senior talent and deliver with juniors. Ask directly who is doing the work.' },
      { _type: 'headingBlock', heading: 'Questions about outcomes' },
      { _type: 'paragraphBlock', text: '"Can you show me work from this category? What did the client say it changed for their business?" Portfolio work is easy to curate. Client outcomes are harder to fake.' },
      { _type: 'paragraphBlock', text: '"What do your clients typically get wrong in the briefing process, and how do you help them avoid it?" A good agency has a clear point of view on this. It also tells you what they\'ll need from you to do their best work.' },
    ],
    processSteps: [
      { label: 'Credentials review', description: 'Portfolio, case studies, and references reviewed before the first call.' },
      { label: 'First call', description: 'Focus on how they think, not what they\'ve done.' },
      { label: 'Reference check', description: 'Talk to 2–3 past clients about the actual experience.' },
      { label: 'Proposal review', description: 'Evaluate whether the proposal reflects understanding of your problem, not just their process.' },
    ],
    faqs: [
      { question: 'How many agencies should we talk to?', answer: 'Two or three. More than that produces comparison fatigue and rarely results in a better decision. Get to a short list quickly based on portfolio and references, then go deep.' },
      { question: 'Should we run a paid pitch or spec work exercise?', answer: 'A small paid exercise can be useful for understanding how an agency thinks. Unpaid spec work for a significant pitch is unreasonable to ask for and typically produces surface-level work that doesn\'t reflect how the agency actually operates.' },
      { question: 'What should we have ready before we start reaching out?', answer: 'A brief that covers: what you\'re trying to accomplish, who your audience is, your timeline, and your budget range. Agencies can\'t scope or recommend the right approach without the basics.' },
    ],
    ctaHeading: 'Evaluating studios right now?',
    ctaBody: 'Tell us what you\'re trying to accomplish. We\'ll give you a straight answer on whether we\'re the right fit.',
  },

}

export const RELATED_SLUGS = {
  'what-does-a-brand-system-include':                  ['brand-guidelines-vs-brand-system', 'when-to-invest-in-a-brand-system', 'how-long-does-a-brand-system-take'],
  'how-long-does-a-brand-system-take':                 ['brand-system-cost', 'what-does-a-brand-system-include', 'when-to-invest-in-a-brand-system'],
  'brand-system-cost':                                 ['how-long-does-a-brand-system-take', 'what-does-a-brand-system-include', 'creative-studio-vs-freelancer'],
  'brand-guidelines-vs-brand-system':                  ['what-does-a-brand-system-include', 'brand-consistency-across-a-team', 'what-is-a-verbal-identity'],
  'when-to-invest-in-a-brand-system':                  ['brand-system-cost', 'how-long-does-a-brand-system-take', 'brand-or-content-first'],
  'what-is-a-verbal-identity':                         ['what-does-a-brand-system-include', 'brand-guidelines-vs-brand-system', 'what-is-a-content-program'],
  'brand-consistency-across-a-team':                   ['brand-guidelines-vs-brand-system', 'what-does-a-brand-system-include', 'when-to-invest-in-a-brand-system'],
  'what-is-a-content-program':                         ['how-to-build-a-b2b-content-program', 'content-program-cost', 'brand-or-content-first'],
  'how-to-build-a-b2b-content-program':                ['what-is-a-content-program', 'content-program-cost', 'how-long-until-content-marketing-works'],
  'content-program-cost':                              ['how-to-build-a-b2b-content-program', 'what-is-a-content-program', 'creative-studio-vs-freelancer'],
  'how-long-until-content-marketing-works':            ['content-program-cost', 'how-to-build-a-b2b-content-program', 'how-to-measure-a-content-program'],
  'what-is-a-thought-leadership-program':              ['what-is-a-content-program', 'how-to-build-a-b2b-content-program', 'brand-or-content-first'],
  'how-to-measure-a-content-program':                  ['what-is-a-content-program', 'how-long-until-content-marketing-works', 'content-program-cost'],
  'what-does-a-digital-product-design-engagement-include': ['how-much-does-product-design-cost', 'how-long-to-design-a-web-app', 'design-system-vs-brand-system'],
  'how-much-does-product-design-cost':                 ['what-does-a-digital-product-design-engagement-include', 'how-long-to-design-a-web-app', 'creative-studio-vs-freelancer'],
  'how-long-to-design-a-web-app':                      ['what-does-a-digital-product-design-engagement-include', 'how-much-does-product-design-cost', 'what-to-look-for-in-a-product-design-studio'],
  'design-system-vs-brand-system':                     ['what-does-a-brand-system-include', 'what-does-a-digital-product-design-engagement-include', 'brand-guidelines-vs-brand-system'],
  'what-to-look-for-in-a-product-design-studio':       ['what-does-a-digital-product-design-engagement-include', 'how-much-does-product-design-cost', 'what-to-ask-a-creative-agency'],
  'brand-or-content-first':                            ['what-does-a-brand-system-include', 'what-is-a-content-program', 'do-i-need-a-brand-system-before-content'],
  'do-i-need-a-brand-system-before-content':           ['brand-or-content-first', 'what-does-a-brand-system-include', 'what-is-a-content-program'],
  'creative-studio-vs-freelancer':                     ['what-to-ask-a-creative-agency', 'brand-system-cost', 'content-program-cost'],
  'what-to-ask-a-creative-agency':                     ['creative-studio-vs-freelancer', 'what-to-look-for-in-a-product-design-studio', 'brand-system-cost'],
}
