import { defineType, defineField } from 'sanity'

export const clientLanding = defineType({
  name: 'clientLanding',
  title: 'Client Landing Page',
  type: 'document',
  fields: [
    defineField({
      name: 'track',
      title: 'Track',
      type: 'string',
      description: "Drives which package set, disciplines, and rate card display. Defaults to Build.",
      options: {
        list: [
          { title: 'Build (foundation, end clients)', value: 'build' },
          { title: 'Grow (fuel, end clients)', value: 'grow' },
          { title: 'Agency (staff aug, white-label)', value: 'agency' },
        ],
        layout: 'radio',
      },
      initialValue: 'build',
    }),
    defineField({
      name: 'anonymizedWorkHeading',
      title: 'Anonymized work strip — heading',
      type: 'string',
      description: 'Agency track only. Optional. e.g. "Work shipped invisibly for other agencies."',
    }),
    defineField({
      name: 'anonymizedWork',
      title: 'Anonymized work strip — items',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Agency track only. e.g. "Global retail brand · brand campaign". Used when most past agency work is NDA-bound.',
    }),
    defineField({
      name: 'name',
      title: 'Internal name',
      type: 'string',
      description: 'For the studio list only, e.g. "Joon Pitch — May 2026"',
      validation: R => R.required(),
    }),
    defineField({
      name: 'slug',
      title: 'URL slug',
      type: 'slug',
      description: 'Lives at /clients/<slug>. Use the client name, lowercase, no spaces.',
      options: { source: 'name' },
      validation: R => R.required(),
    }),
    defineField({
      name: 'password',
      title: 'Password',
      type: 'string',
      description: 'Visitors must enter this to view the page. Speed bump only — readable in JS by anyone who fetches Sanity.',
      validation: R => R.required(),
    }),
    defineField({
      name: 'clientName',
      title: 'Client name (display)',
      type: 'string',
      description: 'Shown in the hero, e.g. "Joon".',
      validation: R => R.required(),
    }),
    defineField({
      name: 'headline',
      title: 'Headline',
      type: 'string',
      description: 'Hero line below the client name.',
    }),
    defineField({
      name: 'intro',
      title: 'Intro paragraph',
      type: 'text',
      rows: 4,
    }),
    defineField({
      name: 'whyHeading',
      title: 'Why-we-sent-this heading',
      type: 'string',
      description: 'Optional. Sits above the framing paragraph, e.g. "Why we put this together."',
    }),
    defineField({
      name: 'whyBody',
      title: 'Why-we-sent-this body',
      type: 'text',
      rows: 4,
      description: 'Optional. 1-paragraph relevance framing connecting your work to their situation.',
    }),
    defineField({
      name: 'foundationHeading',
      title: 'Foundation block heading',
      type: 'string',
      description: 'Optional. Philosophy block, e.g. "Build means foundation."',
    }),
    defineField({
      name: 'foundationBody',
      title: 'Foundation block body',
      type: 'text',
      rows: 6,
      description: 'Optional. 1–2 paragraphs articulating the foundation framing. Blank lines separate paragraphs.',
    }),
    defineField({
      name: 'caseStudies',
      title: 'Featured case studies',
      type: 'array',
      description: 'Drag to reorder. Each links to the existing /work/<slug> page.',
      of: [{ type: 'reference', to: [{ type: 'project' }] }],
    }),
    defineField({
      name: 'packagesHeading',
      title: 'Where-to-start heading',
      type: 'string',
      description: 'Optional. e.g. "Where to start." Sits above the 6 Build packages.',
    }),
    defineField({
      name: 'packagesIntro',
      title: 'Where-to-start intro',
      type: 'text',
      rows: 2,
      description: 'Optional. 1-line framing above the package tiles.',
    }),
    defineField({
      name: 'capabilitiesHeading',
      title: 'Capabilities heading',
      type: 'string',
      description: 'Optional. e.g. "What Build means."',
    }),
    defineField({
      name: 'featuredThoughts',
      title: 'Selected thinking',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'thought' }] }],
      description: 'Optional. 1–3 thought pieces to feature for this prospect.',
    }),
    defineField({
      name: 'testimonialQuote',
      title: 'Testimonial quote',
      type: 'text',
      rows: 3,
      description: 'Optional. A single founder/client quote. 2–3 sentences max.',
    }),
    defineField({
      name: 'testimonialAttribution',
      title: 'Testimonial attribution',
      type: 'string',
      description: 'Optional. e.g. "Stuart Friedman, Founder, Big Buoy".',
    }),
    defineField({
      name: 'trustLogos',
      title: 'Trust strip',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Optional. Client names rendered as a low-contrast row.',
    }),
    defineField({
      name: 'approachHeading',
      title: 'How-we-would-work heading',
      type: 'string',
      description: 'Optional. e.g. "How we\'d work together." Leave blank to hide.',
    }),
    defineField({
      name: 'approachBullets',
      title: 'How-we-would-work bullets',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Optional. 2–4 short lines on engagement model, team, timeline. Leave blank to hide.',
    }),
    defineField({
      name: 'faqHeading',
      title: 'FAQ heading',
      type: 'string',
      description: 'Optional. e.g. "Common questions."',
    }),
    defineField({
      name: 'faqs',
      title: 'FAQs',
      type: 'array',
      of: [{
        type: 'object',
        name: 'faq',
        fields: [
          { name: 'question', title: 'Question', type: 'string', validation: R => R.required() },
          { name: 'answer', title: 'Answer', type: 'text', rows: 3, validation: R => R.required() },
        ],
        preview: { select: { title: 'question', subtitle: 'answer' } },
      }],
      description: 'Optional. 4–8 short Q/A pairs. Shown as a plain list, no accordion.',
    }),
    defineField({
      name: 'signoff',
      title: 'Signoff line',
      type: 'string',
      description: 'Optional. Personal closer above the CTA, e.g. "Talk soon, Chris."',
    }),
    defineField({
      name: 'closingLinkText',
      title: 'Secondary link text',
      type: 'string',
      description: 'Optional. e.g. "Or browse all our work."',
    }),
    defineField({
      name: 'closingLinkHref',
      title: 'Secondary link URL',
      type: 'string',
      description: 'Optional. Internal path (e.g. /work) or full URL.',
    }),
    defineField({
      name: 'ctaText',
      title: 'CTA text',
      type: 'string',
      description: 'Button label at the bottom of the page (e.g. "Get in touch").',
    }),
    defineField({
      name: 'ctaHref',
      title: 'CTA link',
      type: 'string',
      description: 'mailto:..., https://..., or a path like /contact.',
    }),
  ],
  preview: {
    select: { title: 'name', subtitle: 'slug.current' },
    prepare: ({ title, subtitle }) => ({ title, subtitle: subtitle ? `/clients/${subtitle}` : '' }),
  },
})
